import {MythrasStdCharacteristicType} from "@prisma/client";

export const skillFormulas: Record<string, (chars: Record<MythrasStdCharacteristicType, number>) => number> = {
    // STANDARD SKILLS
    'Athletics': (chars) => chars.Strength + chars.Dexterity,
    'Boating': (chars) => chars.Strength + chars.Constitution,
    'Brawn': (chars) => chars.Strength + chars.Size,
    'Conceal': (chars) => chars.Dexterity + chars.Power,
    'Customs': (chars) => chars.Intelligence * 2,
    'Dance': (chars) => chars.Dexterity + chars.Charisma,
    'Deceit': (chars) => chars.Intelligence + chars.Charisma,
    'Drive': (chars) => chars.Dexterity + chars.Power,
    'Endurance': (chars) => chars.Constitution * 2,
    'Evade': (chars) => chars.Dexterity * 2,
    'First Aid': (chars) => chars.Intelligence + chars.Dexterity,
    'Influence': (chars) => chars.Charisma * 2,
    'Insight': (chars) => chars.Intelligence + chars.Power,
    'Locale': (chars) => chars.Intelligence * 2,
    'Native Tongue': (chars) => chars.Intelligence + chars.Charisma,
    'Perception': (chars) => chars.Intelligence + chars.Power,
    'Ride': (chars) => chars.Dexterity + chars.Power,
    'Sing': (chars) => chars.Charisma + chars.Power,
    'Stealth': (chars) => chars.Dexterity + chars.Intelligence,
    'Swim': (chars) => chars.Strength + chars.Constitution,
    'Unarmed': (chars) => chars.Strength + chars.Dexterity,
    'Willpower': (chars) => chars.Power * 2,

    // PROFESSIONAL SKILLS
    'Acting': (chars) => chars.Charisma * 2,
    'Acrobatics': (chars) => chars.Strength + chars.Dexterity,
    'Art': (chars) => chars.Power + chars.Charisma,
    'Bureaucracy': (chars) => chars.Intelligence * 2,
    'Commerce': (chars) => chars.Intelligence + chars.Charisma,
    'Courtesy': (chars) => chars.Intelligence + chars.Charisma,
    'Craft': (chars) => chars.Dexterity + chars.Intelligence,
    'Culture': (chars) => chars.Intelligence * 2,
    'Disguise': (chars) => chars.Intelligence + chars.Charisma,
    'Engineering': (chars) => chars.Intelligence * 2,
    'Gambling': (chars) => chars.Intelligence + chars.Power,
    'Healing': (chars) => chars.Intelligence + chars.Power,
    'Language': (chars) => chars.Intelligence + chars.Charisma,
    'Literacy': (chars) => chars.Intelligence * 2,
    'Lockpicking': (chars) => chars.Dexterity * 2,
    'Lore': (chars) => chars.Intelligence * 2,
    'Mechanisms': (chars) => chars.Dexterity + chars.Intelligence,
    'Musicianship': (chars) => chars.Dexterity + chars.Charisma,
    'Navigation': (chars) => chars.Intelligence + chars.Power,
    'Oratory': (chars) => chars.Power + chars.Charisma,
    'Seamanship': (chars) => chars.Intelligence + chars.Constitution,
    'Seduction': (chars) => chars.Intelligence + chars.Charisma,
    'Sleight': (chars) => chars.Dexterity + chars.Charisma,
    'Streetwise': (chars) => chars.Power + chars.Charisma,
    'Survival': (chars) => chars.Constitution + chars.Power,
    'Teach': (chars) => chars.Intelligence + chars.Charisma,
    'Track': (chars) => chars.Intelligence + chars.Constitution,

    // MAGICAL SKILLS
    'Binding': (chars) => chars.Power + chars.Charisma,
    'Devotion': (chars) => chars.Power + chars.Charisma,
    'Exhort': (chars) => chars.Intelligence + chars.Charisma,
    'Folk Magic': (chars) => chars.Power + chars.Charisma,
    'Invocation': (chars) => chars.Intelligence * 2,
    'Meditation': (chars) => chars.Intelligence + chars.Constitution,
    'Mysticism': (chars) => chars.Power + chars.Constitution,
    'Shaping': (chars) => chars.Intelligence + chars.Power,
    'Trance': (chars) => chars.Power + chars.Constitution,
};